name: table_generator
description: A code generator that generates SQL creation code for annotated classes.
version: 0.0.1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^5.12.0
  build: ^2.3.0
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.4.6