name: table_generator
description: A code generator that generates SQL creation code for annotated classes.
version: 0.0.3
environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  analyzer: 6.8.0
  build: 2.4.1
  source_gen: 1.5.0
# dependency_overrides: 
#   macros: 0.1.3-main.0

dev_dependencies:
  build_runner: 2.4.13